# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hipster_sql_to_hbase"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jean Lescure"]
  s.date = "2014-02-21"
  s.description = "SQL to HBase parser using Treetop (output based on Thrift)."
  s.email = "jeanmlescure@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "hipster_sql_to_hbase.gemspec",
    "lib/hipster_sql_to_hbase.rb",
    "lib/sql_parser/sql.treetop",
    "lib/sql_parser/sql_chars.treetop",
    "lib/sql_parser/sql_create_table.treetop",
    "lib/sql_parser/sql_datatypes.treetop",
    "lib/sql_parser/sql_delete.treetop",
    "lib/sql_parser/sql_drop_table.treetop",
    "lib/sql_parser/sql_from_clause.treetop",
    "lib/sql_parser/sql_group_by_clause.treetop",
    "lib/sql_parser/sql_helpers.treetop",
    "lib/sql_parser/sql_insert.treetop",
    "lib/sql_parser/sql_key_value_pair.treetop",
    "lib/sql_parser/sql_limit.treetop",
    "lib/sql_parser/sql_order_by_clause.treetop",
    "lib/sql_parser/sql_primitives.treetop",
    "lib/sql_parser/sql_row_support.treetop",
    "lib/sql_parser/sql_select.treetop",
    "lib/sql_parser/sql_select_clause.treetop",
    "lib/sql_parser/sql_show_tables.treetop",
    "lib/sql_parser/sql_tokens.treetop",
    "lib/sql_parser/sql_transaction.treetop",
    "lib/sql_parser/sql_truncate.treetop",
    "lib/sql_parser/sql_where_condition.treetop",
    "test/helper.rb",
    "test/test_hipster_sql_to_hbase.rb"
  ]
  s.homepage = "http://github.com/jeanlescure/hipster_sql_to_hbase"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "SQL to HBase parser using Treetop (output based on Thrift)."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<treetop>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<treetop>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<treetop>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

